### PR TITLE
lv bms tester board hardware review 

### PR DESCRIPTION
**Pull request by aramachandran7**
See https://docs.google.com/document/d/1hcEqd_f59n61Hw5GQk4uWy7O5cFY6wYL8yzSQNkAr8U/edit#

### CODE REVIEW

**Comment by jack-greenberg** [comment]
Can you move the folder to `vehicle/mkv/hardware/lvbox/lvbms/tester_board`?

**Review by jack-greenberg — COMMENTED** [review]
Can you move the folder to `vehicle/mkv/hardware/lvbox/lvbms/tester_board`?

**Comment by aramachandran7** [comment]
> Can you move the folder to `vehicle/mkv/hardware/lvbox/lvbms/tester_board`?

Done. Apologies for delay.

**Review by aditya-sudhakar — APPROVED** [review]
looks good

**Pull request merged**
